FROM node:lts-alpine
# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
RUN apk add make gcc g++ python3 
RUN npm install
RUN npm rebuild bcrypt
RUN apk del make gcc g++ python3

# add app
COPY . ./

# start app
CMD ["npm", "start"]
