version: '3.4'

services:
  foosball:
    image: foosball
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    # env_file:
    #   - ./.env
    ports:
      - 3000:3000
    networks:
      - foosball-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    networks:
      - foosball-app
    volumes:
      - mongo-data:/data/db
networks:
  foosball-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local